package workspace

import (
	"fmt"
	"path/filepath"
	"strings"
)

// SchemaVersion is the version of the Daedalus *workspace schema* — the shape
// and contract of the `.daedalus/` layout and its manifest. It is deliberately
// distinct from buildinfo.Version, which identifies the *binary*: the workspace
// format and the binary evolve on independent cadences (many binary releases
// can target the same schema, and a schema bump is a migration concern, not a
// build artifact). Embedding the binary version here would make every manifest
// churn on every release and break the byte-for-byte determinism golden files
// rely on (RNF-5). When the manifest layout changes in a breaking way, bump
// this constant and add an upgrade path (ticket 01-02 territory).
const SchemaVersion = "1"

// DefaultBackend is the target backend written into a fresh manifest. The MVP
// ships a single adapter — Claude Code (PRD D3) — so it is the deterministic
// default. The interactive *selection* of backends is ticket 01-04's job; this
// package only guarantees the field exists with a sensible default.
const DefaultBackend = "claude-code"

// Manifest is the in-memory model of `.daedalus/daedalus.yaml`. Its fields are
// declared in the exact order they must appear in the rendered file; the
// renderer walks them top-to-bottom, so the struct itself is the single source
// of truth for key order (R4/CA4 — stable, diff-friendly ordering).
type Manifest struct {
	// Name is the project name, derived deterministically from the target
	// directory (see deriveProjectName) unless overridden.
	Name string
	// Version is the workspace schema version (SchemaVersion), not the binary
	// version.
	Version string
	// Backends are the target agent backends, in declaration order. Defaults to
	// a single MVP entry; ticket 01-04 owns effective selection.
	Backends []string
	// Conventions captures the project conventions mirrored from init.md §7,
	// rendered as an ordered nested mapping.
	Conventions []convention
}

// convention is a single ordered key/value of the manifest's `conventions`
// block. A slice of these (rather than a map) preserves order across runs,
// which a Go map cannot guarantee.
type convention struct {
	Key   string
	Value string
}

// newManifest builds the manifest for a target whose project name has already
// been derived and whose target backends have been resolved. It is pure: same
// name and backends in, same manifest out, which is what makes the rendered file
// reproducible (R7/CA6). An empty backends slice falls back to the MVP default
// so the manifest always carries at least one backend, even if a caller bypasses
// the normalizing path.
func newManifest(name string, backends []string) Manifest {
	if len(backends) == 0 {
		backends = []string{DefaultBackend}
	}
	return Manifest{
		Name:     name,
		Version:  SchemaVersion,
		Backends: backends,
		Conventions: []convention{
			// Mirrors init.md §7 so the manifest never contradicts the documented
			// conventions. Order here is the order rendered.
			{Key: "naming", Value: "kebab-case"},
			{Key: "markdown", Value: "hierarchical-headings"},
			{Key: "yaml", Value: "ordered-deterministic"},
		},
	}
}

// renderManifest serializes a Manifest to deterministic YAML using only the
// standard library. We render by hand instead of pulling in a YAML dependency
// (go.mod has none, and stdlib-first is the rule): the manifest is a small,
// fixed shape of scalars and short string lists, so a hand-rolled renderer is
// simpler and — crucially — gives us *guaranteed* key order without relying on
// a library's map-sorting behavior. Output ends with a trailing newline and is
// byte-for-byte stable for a given Manifest (R3/CA3).
func renderManifest(m Manifest) string {
	var b strings.Builder

	b.WriteString("# Daedalus workspace manifest.\n")
	b.WriteString("# Generated by `daedalus init`. Keys are ordered and stable for clean diffs.\n")

	writeScalar(&b, "name", m.Name)
	writeScalar(&b, "version", m.Version)

	b.WriteString("backends:\n")
	for _, backend := range m.Backends {
		fmt.Fprintf(&b, "  - %s\n", yamlScalar(backend))
	}

	b.WriteString("conventions:\n")
	for _, c := range m.Conventions {
		fmt.Fprintf(&b, "  %s: %s\n", c.Key, yamlScalar(c.Value))
	}

	return b.String()
}

// writeScalar writes a `key: value` line with a YAML-safe value.
func writeScalar(b *strings.Builder, key, value string) {
	fmt.Fprintf(b, "%s: %s\n", key, yamlScalar(value))
}

// yamlScalar renders a string as a YAML scalar, quoting it only when the plain
// form could be misread by a parser. The generated values are simple
// identifiers, but the project name comes from a directory name and can contain
// characters (leading digits, spaces, ':', '#', …) that require quoting to keep
// the output valid YAML.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if needsQuoting(s) {
		// Double-quote and escape backslashes and quotes — enough for the
		// printable directory-name characters we expect.
		escaped := strings.ReplaceAll(s, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		return `"` + escaped + `"`
	}
	return s
}

// needsQuoting reports whether a YAML scalar must be quoted to round-trip
// safely. It is intentionally conservative: when in doubt, quote.
func needsQuoting(s string) bool {
	if s != strings.TrimSpace(s) {
		return true // leading/trailing whitespace is significant only when quoted
	}
	// Indicator characters and tokens that change meaning if left bare.
	switch s {
	case "true", "false", "null", "yes", "no", "on", "off", "~":
		return true
	}
	if first := s[0]; first >= '0' && first <= '9' {
		return true // could be parsed as a number
	}
	return strings.ContainsAny(s, ":#{}[],&*!|>'\"%@`")
}

// renderInitMD produces the base init.md for the target project. It mirrors the
// structure of Daedalus's own init.md (vision/purpose, the §4.2 `.daedalus/`
// structure map, conventions, references) instantiated for the project, and is
// fully deterministic for a given project name (R2/R3/CA2).
func renderInitMD(name string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s — `init.md` (project master guideline)\n\n", name)
	b.WriteString("> **Purpose:** this is the entry point for the project's AI structure. ")
	b.WriteString("Any person — or agent — working on this project reads it first. ")
	b.WriteString("It defines the vision, conventions, the layout map and the references ")
	b.WriteString("so work can start without ambiguity.\n>\n")
	b.WriteString("> Generated by `daedalus init`. Replace the placeholder sections with ")
	b.WriteString("your project's specifics.\n\n")
	b.WriteString("---\n\n")

	b.WriteString("## 1. Vision & purpose\n\n")
	fmt.Fprintf(&b, "_Describe what **%s** is, the problem it solves and who it is for._ ", name)
	b.WriteString("This section is a placeholder; fill it in with the project's brief.\n\n")
	b.WriteString("---\n\n")

	b.WriteString("## 2. Workspace structure (`.daedalus/`)\n\n")
	b.WriteString("The canonical, backend-agnostic source of truth for this project's AI ")
	b.WriteString("structure lives under `.daedalus/`:\n\n")
	b.WriteString(structureMap())
	b.WriteString("\n---\n\n")

	b.WriteString("## 3. Conventions\n\n")
	b.WriteString("- **Naming:** `kebab-case` for files/ids of epics, tickets, agents and workflows.\n")
	b.WriteString("- **Markdown:** hierarchical headings, tables for metadata, code blocks for schemas/DAGs.\n")
	b.WriteString("- **YAML:** stable, ordered keys (deterministic output, clean diffs).\n")
	b.WriteString("- **Git:** branch per epic/ticket; descriptive commits; the backlog state is versioned.\n")
	b.WriteString("- **Idempotency:** `build`/`sync` never destroys manual changes outside the managed area; it always offers a preview/diff.\n")
	b.WriteString("- **Traceability:** every ticket references its epic; every epic references its source spec/architecture.\n\n")
	b.WriteString("---\n\n")

	b.WriteString("## 4. References\n\n")
	b.WriteString("- `.daedalus/daedalus.yaml` — workspace manifest (name, version, backends, conventions).\n")
	b.WriteString("- `.daedalus/specs/` — spec / PRD for this project.\n")
	b.WriteString("- `.daedalus/workflows/` — declarative DAG workflows.\n")

	return b.String()
}

// renderStateReadme produces the deterministic placeholder that materializes the
// progress-state directory `.daedalus/.state/` as a git-tracked location. Git
// cannot track an empty directory, so without a tracked file inside it the state
// directory would silently vanish from the repository — breaking the RF-8.1
// guarantee that all relevant state is git-versioned and portable across the
// team. This README is that anchor: it is the single tracked file whose only job
// is to keep `.state/` present in git and to document, in plain text, that the
// directory holds progress state and is intentionally versioned (PRD §8.2,
// init.md §4.2/§7).
//
// The content is intentionally static — no project name, no timestamps, no
// volatile fields — so it is byte-for-byte identical on every run and never
// introduces diff noise (RNF-6); the deterministic serialization of the actual
// state entries that will live here is ticket 08-02's concern.
func renderStateReadme() string {
	var b strings.Builder
	b.WriteString("# `.state/` — progress state (git-tracked)\n\n")
	b.WriteString("This directory holds Daedalus's **progress state** for this project ")
	b.WriteString("(e.g. which backlog steps have run and their outcomes).\n\n")
	b.WriteString("It is **canonical, relevant state**: it is committed to git on purpose so ")
	b.WriteString("the whole team shares one source of truth and the project stays portable ")
	b.WriteString("across machines. Do **not** add it to `.gitignore`.\n\n")
	b.WriteString("State is stored as plain text (YAML/Markdown) for clean diffs and merges. ")
	b.WriteString("This README is a tracked placeholder so the directory persists in git even ")
	b.WriteString("while empty; Daedalus never deletes your files here.\n\n")
	b.WriteString("> Generated by `daedalus init`. Safe to keep; safe to extend.\n")
	return b.String()
}

// structureMap renders the `.daedalus/` layout (init.md §4.2) as a fenced code
// block. Kept in sync with Subdirs and RootArtifacts so the documented map can
// never contradict what the scaffolding actually creates (R5).
func structureMap() string {
	var b strings.Builder
	b.WriteString("```\n")
	b.WriteString(".daedalus/\n")
	b.WriteString("  daedalus.yaml        # manifest: name, backend(s), version, conventions\n")
	b.WriteString("  init.md              # this project master guideline\n")
	b.WriteString("  agents/              # backend-agnostic agent definitions (yaml + prompt md)\n")
	b.WriteString("  prompts/             # global/shared prompts\n")
	b.WriteString("  workflows/           # declarative DAG workflows (yaml)\n")
	b.WriteString("  specs/               # spec / PRD\n")
	b.WriteString("  architecture/        # architecture documents\n")
	b.WriteString("  epics/               # epics\n")
	b.WriteString("  tickets/             # tickets\n")
	b.WriteString("  docs/                # derived documentation\n")
	b.WriteString("  .state/              # progress state (git-tracked)\n")
	b.WriteString("```\n")
	return b.String()
}

// deriveProjectName returns the deterministic project name for a target root:
// the base name of the root resolved to an absolute path. Resolving to absolute
// is what lets "." (the common `daedalus init` invocation) yield the repo's
// directory name instead of literally ".". Same directory in → same name out,
// which keeps the manifest reproducible (R7/CA4).
func deriveProjectName(root string) string {
	abs, err := filepath.Abs(root)
	if err != nil {
		// Abs only fails when the working directory can't be resolved; fall back
		// to the cleaned input so we still produce a stable, non-empty name.
		abs = filepath.Clean(root)
	}
	name := filepath.Base(abs)
	// filepath.Base returns "." or a separator for degenerate paths (e.g. root
	// of a drive); guard so the manifest never carries a meaningless name.
	if name == "." || name == string(filepath.Separator) {
		return "project"
	}
	return name
}

// artifactContent returns the deterministic content for a root artifact given
// the resolved project name and target backends. The bool reports whether the
// artifact has managed content; unknown artifacts (none today) return false so
// callers create them empty, preserving forward-compatibility if new root files
// are added. backends only affects the manifest; other artifacts ignore it.
func artifactContent(artifact, name string, backends []string) (string, bool) {
	switch artifact {
	case "daedalus.yaml":
		return renderManifest(newManifest(name, backends)), true
	case "init.md":
		return renderInitMD(name), true
	case StateReadme:
		// The state placeholder is static (see renderStateReadme); name/backends
		// are intentionally ignored to keep it byte-for-byte stable across runs.
		return renderStateReadme(), true
	default:
		return "", false
	}
}
