package workspace

import (
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// updateGolden, when set (go test ./internal/workspace -run Golden -update),
// rewrites the golden files from the current renderer output instead of
// comparing. The goldens are generated by the code and then reviewed, never
// hand-edited, so the snapshot always reflects exactly what the scaffolding
// emits. This mirrors the adapter golden harness in internal/compile and is the
// RF-8.2 / RNF-5 guarantee that the canonical workspace state is
// snapshot-verifiable.
var updateGolden = flag.Bool("update", false, "rewrite golden files from current output")

// goldenWorkspaceArtifacts are the canonical workspace state files whose exact
// bytes are pinned by golden snapshots: the manifest, the project init.md and
// the git-tracked progress-state placeholder. Paths are workspace-relative.
// Backlog/agent/prompt/workflow families are covered by golden tests in their
// own packages (each owns its renderer); this set is the workspace-root state.
var goldenWorkspaceArtifacts = []string{
	"daedalus.yaml",
	"init.md",
	StateReadme,
}

// TestWorkspaceGolden scaffolds a workspace under a fixed-name root (so the
// derived project name — and thus the rendered content — is stable) and asserts
// each canonical state artifact matches its golden file byte-for-byte. Run with
// -update to regenerate after an intentional format change.
func TestWorkspaceGolden(t *testing.T) {
	root := fixedNameRoot(t, "golden-project")
	if _, err := Create(root); err != nil {
		t.Fatalf("Create: %v", err)
	}

	for _, rel := range goldenWorkspaceArtifacts {
		got, err := os.ReadFile(filepath.Join(root, Name, filepath.FromSlash(rel)))
		if err != nil {
			t.Fatalf("read artifact %s: %v", rel, err)
		}
		assertGolden(t, rel, got)
	}
}

// assertGolden compares got against the golden snapshot for rel (a slash path),
// or rewrites it when -update is set. The golden tree mirrors the artifact's
// workspace-relative path under testdata/golden/, so the snapshot reads like a
// real workspace.
func assertGolden(t *testing.T, rel string, got []byte) {
	t.Helper()
	goldenPath := filepath.Join("testdata", "golden", filepath.FromSlash(rel))

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("mkdir golden dir: %v", err)
		}
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("write golden %s: %v", goldenPath, err)
		}
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden %s: %v (run with -update to generate)", goldenPath, err)
	}
	if string(want) != string(got) {
		t.Errorf("artifact %s does not match golden:\n--- got ---\n%s\n--- want ---\n%s",
			rel, got, want)
	}
}
