package compile

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/Codigo-de-Altura/Daedalus/internal/catalog"
)

// updateGolden, when set (go test ./internal/compile -run Golden -update), rewrites
// the golden files from the current renderer output instead of comparing. The
// goldens are generated by the code and then reviewed, never hand-edited, so the
// snapshot always reflects exactly what the adapter emits (RNF-5).
var updateGolden = flag.Bool("update", false, "rewrite golden files from current output")

// goldenDefinition is a fixed, hand-built canonical Definition that exercises the
// adapter's mapping surface deterministically:
//   - an agent WITH a model parameter (emits the `model` frontmatter key),
//   - an agent WITHOUT a model parameter (omits it) and with a value that needs
//     quoting in its role (a colon),
//   - a command WITH a description, and a command WITHOUT one (no frontmatter).
//
// Agents and commands are listed id-sorted, exactly as LoadDefinition delivers
// them, so the golden order matches a real build.
func goldenDefinition() Definition {
	return Definition{
		Agents: []catalog.Agent{
			{
				ID:     "analyst",
				Role:   "Requirements analyst: turns a brief into a spec",
				Prompt: "You are the analyst.\nRefine the brief into a spec.",
			},
			{
				ID:     "architect",
				Role:   "System architect",
				Prompt: "You are the architect.",
				Params: []catalog.Param{
					{Key: "model", Type: catalog.ParamString, Value: "opus"},
				},
			},
		},
		Commands: []Command{
			{ID: "commit-policy", Description: "", Body: "Use Conventional Commits."},
			{ID: "project-style", Description: "Project style guide", Body: "Write in English.\nBe concise."},
		},
	}
}

// TestClaudeGolden compiles the fixed definition and asserts each artifact matches
// its golden file byte-for-byte (REQ-8: deterministic, snapshot-verifiable
// output). Run with -update to regenerate after an intentional format change.
func TestClaudeGolden(t *testing.T) {
	c := newClaudeCompiler()
	arts, err := c.Compile(goldenDefinition())
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}

	for _, f := range arts.Files {
		// The golden path mirrors the artifact's RelPath under testdata/, so the
		// snapshot tree reads like a real `.claude/` directory.
		goldenPath := filepath.Join("testdata", "golden", filepath.FromSlash(f.RelPath))

		if *updateGolden {
			if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
				t.Fatalf("mkdir golden dir: %v", err)
			}
			if err := os.WriteFile(goldenPath, []byte(f.Content), 0o644); err != nil {
				t.Fatalf("write golden %s: %v", goldenPath, err)
			}
			continue
		}

		want, err := os.ReadFile(goldenPath)
		if err != nil {
			t.Fatalf("read golden %s: %v (run with -update to generate)", goldenPath, err)
		}
		if string(want) != f.Content {
			t.Errorf("artifact %s does not match golden:\n--- got ---\n%s\n--- want ---\n%s",
				f.RelPath, f.Content, string(want))
		}
	}
}

// TestClaudeCompileDeterministic covers REQ-8 directly: compiling the same
// definition twice yields identical artifacts in identical order, byte-for-byte.
func TestClaudeCompileDeterministic(t *testing.T) {
	c := newClaudeCompiler()
	first, err := c.Compile(goldenDefinition())
	if err != nil {
		t.Fatalf("first compile: %v", err)
	}
	second, err := c.Compile(goldenDefinition())
	if err != nil {
		t.Fatalf("second compile: %v", err)
	}
	if len(first.Files) != len(second.Files) {
		t.Fatalf("artifact count differs: %d vs %d", len(first.Files), len(second.Files))
	}
	for i := range first.Files {
		if first.Files[i] != second.Files[i] {
			t.Errorf("artifact %d differs between runs:\n%+v\nvs\n%+v",
				i, first.Files[i], second.Files[i])
		}
	}
}

// TestClaudeArtifactOrderAndNames covers REQ-9 and the stable emission order:
// agents first (id-sorted), then commands (id-sorted), then settings.json, with
// kebab-case file names derived from the canonical id.
func TestClaudeArtifactOrderAndNames(t *testing.T) {
	c := newClaudeCompiler()
	arts, err := c.Compile(goldenDefinition())
	if err != nil {
		t.Fatalf("Compile: %v", err)
	}
	want := []string{
		".claude/agents/analyst.md",
		".claude/agents/architect.md",
		".claude/commands/commit-policy.md",
		".claude/commands/project-style.md",
		".claude/settings.json",
	}
	if len(arts.Files) != len(want) {
		t.Fatalf("got %d artifacts, want %d: %v", len(arts.Files), len(want), relPaths(arts))
	}
	for i, w := range want {
		if arts.Files[i].RelPath != w {
			t.Errorf("artifact[%d] = %q, want %q", i, arts.Files[i].RelPath, w)
		}
	}
}

// TestClaudeSettingsIsValidJSON covers REQ-7 ("settings bien formados"): the
// generated settings.json parses as JSON and carries the honest managed marker —
// and only that, plus $schema. We assert it fabricates no permissions/env/hooks.
func TestClaudeSettingsIsValidJSON(t *testing.T) {
	var parsed map[string]any
	if err := json.Unmarshal([]byte(renderSettings()), &parsed); err != nil {
		t.Fatalf("settings.json is not valid JSON: %v", err)
	}
	if _, ok := parsed["$schema"]; !ok {
		t.Error("settings.json missing $schema")
	}
	dae, ok := parsed["daedalus"].(map[string]any)
	if !ok {
		t.Fatalf("settings.json missing daedalus marker object; got %v", parsed["daedalus"])
	}
	if dae["managed"] != true {
		t.Errorf("daedalus.managed = %v, want true", dae["managed"])
	}
	// Honesty check: no fabricated Claude Code config keys.
	for _, forbidden := range []string{"permissions", "env", "hooks", "model"} {
		if _, present := parsed[forbidden]; present {
			t.Errorf("settings.json fabricates a %q key it has no source for", forbidden)
		}
	}
}

func relPaths(a Artifacts) []string {
	out := make([]string, len(a.Files))
	for i, f := range a.Files {
		out[i] = f.RelPath
	}
	return out
}
