package compile

import (
	"errors"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
)

// ArtifactStatus classifies what a single produced artifact's write would do,
// computed by comparing the target content against what is already on disk. It is
// the unit of the idempotent, non-destructive write strategy (RF-6.3) and the
// data a preview (RF-6.4) renders.
type ArtifactStatus int

const (
	// StatusCreated: the artifact does not exist on disk yet; a build writes it.
	StatusCreated ArtifactStatus = iota
	// StatusUpdated: the artifact exists but its content differs from the target;
	// a build rewrites it (atomically). This only happens when the canonical
	// definition changed (REQ-6) — a re-run over an unchanged definition produces
	// byte-identical content and so never updates.
	StatusUpdated
	// StatusUnchanged: the on-disk content is byte-identical to the target; a build
	// leaves the file completely untouched — no write, no mtime churn (REQ-2: no
	// spurious changes).
	StatusUnchanged
)

// String renders a status as a short, stable label for logs and previews.
func (s ArtifactStatus) String() string {
	switch s {
	case StatusCreated:
		return "created"
	case StatusUpdated:
		return "updated"
	case StatusUnchanged:
		return "unchanged"
	default:
		return "unknown"
	}
}

// PlannedArtifact pairs a produced artifact with the status its write would have,
// plus the two contents a preview needs to render a diff WITHOUT reading disk or
// recompiling (RF-6.4). It carries the relative path (slash form, stable across
// OSes) so a caller can report or diff straight from this value.
//
// Target and Current are the whole point of the enrichment: the presentation layer
// (Padmé's TUI) diffs Current → Target itself and never touches the filesystem,
// keeping the strict presentation/core split the rest of the tui package follows.
type PlannedArtifact struct {
	// RelPath is the artifact's repo-relative path in slash form.
	RelPath string
	// Status is what writing this artifact would do (created/updated/unchanged).
	Status ArtifactStatus
	// Target is the new content the compiler produced for this artifact — what a
	// build would write. It is always populated.
	Target string
	// Current is the content currently on disk at RelPath: empty for a StatusCreated
	// artifact (the file does not exist yet), and the existing bytes otherwise. For
	// StatusUnchanged it equals Target; for StatusUpdated it differs. The preview
	// diffs Current → Target; a caller must use Status (not an empty Current) to
	// tell "created" from "an existing empty file", since both yield Current == "".
	Current string
}

// BackendPlan is the pure, side-effect-free classification of one backend's
// artifacts against the current on-disk state: what a build would create, update
// or leave unchanged, plus any orphans it detected. Holding a BackendPlan writes
// nothing, so RF-6.4 can render it as a preview/diff and the build's Apply step
// consumes the same value — detection and writing share one source of truth,
// mirroring the workspace package's Plan/Apply split.
type BackendPlan struct {
	// Backend is the backend key this plan is for.
	Backend string
	// Artifacts are the produced artifacts with their per-file status, in the
	// compiler's deterministic emission order (RNF-5).
	Artifacts []PlannedArtifact
	// Orphans are files that live inside the managed directories but are NOT in the
	// current produced set — typically an artifact generated by a previous build
	// whose canonical source was since removed. They are DETECTED and exposed for a
	// preview (RF-6.4) to show, but NEVER deleted by this package: the default is
	// safe and non-destructive (REQ-5/Check-8). Paths are repo-relative, slash form,
	// in sorted order.
	Orphans []string
}

// managedArea returns the set of repo-relative paths (slash form) a backend's
// artifacts occupy — the EXACT, explicit, deterministic managed area (REQ-1/REQ-7).
// It is derived solely from what the compiler produces for the current canonical
// definition, so it never depends on execution order, the environment, or a
// persisted record of past builds. The build touches only these paths; everything
// else on disk is outside the managed area and is preserved (REQ-3).
func managedArea(arts Artifacts) map[string]struct{} {
	set := make(map[string]struct{}, len(arts.Files))
	for _, f := range arts.Files {
		set[f.RelPath] = struct{}{}
	}
	return set
}

// managedDirs returns the distinct parent directories (repo-relative, slash form)
// the produced artifacts live in. Orphan detection scans exactly these directories
// and no others, so the build never reads — let alone reasons about — files in
// parts of the tree it does not manage (REQ-1).
func managedDirs(arts Artifacts) []string {
	seen := make(map[string]struct{})
	var dirs []string
	for _, f := range arts.Files {
		d := path.Dir(f.RelPath)
		if d == "." {
			continue
		}
		if _, ok := seen[d]; !ok {
			seen[d] = struct{}{}
			dirs = append(dirs, d)
		}
	}
	sort.Strings(dirs)
	return dirs
}

// PlanArtifacts classifies a backend's produced artifacts against the on-disk
// state under root WITHOUT writing anything (REQ-2/RF-6.4). For each artifact it
// compares the target content to the current file: absent ⇒ created, present and
// different ⇒ updated, present and byte-identical ⇒ unchanged. It also detects
// orphans — files in the managed directories that are not in the produced set —
// and exposes them without touching them.
//
// It is deterministic: artifacts keep the compiler's emission order and orphans
// are sorted, so the same workspace state yields the same plan.
func PlanArtifacts(root string, arts Artifacts) (BackendPlan, error) {
	plan := BackendPlan{Backend: arts.Backend}

	for _, f := range arts.Files {
		status, current, err := classify(root, f)
		if err != nil {
			return BackendPlan{}, err
		}
		plan.Artifacts = append(plan.Artifacts, PlannedArtifact{
			RelPath: f.RelPath,
			Status:  status,
			Target:  f.Content,
			Current: current,
		})
	}

	orphans, err := detectOrphans(root, arts)
	if err != nil {
		return BackendPlan{}, err
	}
	plan.Orphans = orphans

	return plan, nil
}

// classify compares one artifact's target content to what is on disk and returns
// its status AND the current on-disk content (empty when the file does not exist),
// so callers that need the bytes for a diff (PlanArtifacts) do not read the file a
// second time. A read error other than "not exist" is surfaced (it is a real I/O
// problem, not a classification outcome).
func classify(root string, f Artifact) (status ArtifactStatus, current string, err error) {
	abs := filepath.Join(root, filepath.FromSlash(f.RelPath))
	b, err := os.ReadFile(abs)
	switch {
	case errors.Is(err, fs.ErrNotExist):
		return StatusCreated, "", nil
	case err != nil:
		return StatusUnchanged, "", err
	}
	current = string(b)
	if current == f.Content {
		return StatusUnchanged, current, nil
	}
	return StatusUpdated, current, nil
}

// detectOrphans lists files inside the managed directories that the current build
// does not produce. These are exposed for a preview to surface (RF-6.4) and are
// never deleted here (REQ-5/Check-8: safe default). The scan is shallow per managed
// directory — the layout puts artifacts directly in `.claude/agents`,
// `.claude/commands`, etc. — and skips subdirectories and our own temp files so a
// concurrent write is never mistaken for an orphan. A managed directory that does
// not exist yet simply contributes no orphans.
func detectOrphans(root string, arts Artifacts) ([]string, error) {
	produced := managedArea(arts)
	var orphans []string

	for _, dir := range managedDirs(arts) {
		absDir := filepath.Join(root, filepath.FromSlash(dir))
		entries, err := os.ReadDir(absDir)
		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				continue
			}
			return nil, err
		}
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			rel := dir + "/" + e.Name()
			if _, isProduced := produced[rel]; isProduced {
				continue
			}
			// Skip our own atomic-write temp files (".<base>.tmp-*"): they are
			// transient and never user content.
			if isTempArtifact(e.Name()) {
				continue
			}
			orphans = append(orphans, rel)
		}
	}

	sort.Strings(orphans)
	return orphans, nil
}

// isTempArtifact reports whether name is one of writeAtomic's in-flight temp files
// (".<base>.tmp-*"). They must never be classified as orphans (or as user content).
func isTempArtifact(name string) bool {
	return len(name) > 0 && name[0] == '.' && containsTmpMarker(name)
}

// containsTmpMarker reports whether name carries the ".tmp-" marker writeAtomic
// uses for its temporary files.
func containsTmpMarker(name string) bool {
	const marker = ".tmp-"
	for i := 0; i+len(marker) <= len(name); i++ {
		if name[i:i+len(marker)] == marker {
			return true
		}
	}
	return false
}
