package catalog

import (
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// updateGolden, when set (go test ./internal/catalog -run Golden -update),
// rewrites the golden files from the current renderer output instead of
// comparing. Mirrors the adapter golden harness in internal/compile: goldens are
// generated by the code and reviewed, never hand-edited, so the snapshot always
// reflects exactly what the canonical agent renderer emits (RF-8.2 / RNF-5).
var updateGolden = flag.Bool("update", false, "rewrite golden files from current output")

// goldenAgent is a fixed canonical agent that exercises the definition renderer's
// surface deterministically: a typed parameter (string), a role containing a
// colon (so the conservative YAML quoting kicks in) and a multi-line prompt. It
// is hand-built so its rendered bytes are reproducible and snapshot-stable.
func goldenAgent() Agent {
	return Agent{
		ID:   "analyst",
		Role: "Requirements analyst: turns a brief into a spec",
		Params: []Param{
			{Key: "model", Type: ParamString, Value: "default"},
		},
		Prompt: "You are the analyst.\nRefine the brief into a spec.\n",
	}
}

// TestCatalogGolden renders the canonical agent definition (agent.yaml) and its
// prompt (prompt.md) and asserts each matches its golden file byte-for-byte. Run
// with -update to regenerate after an intentional format change.
func TestCatalogGolden(t *testing.T) {
	a := goldenAgent()
	cases := []struct {
		name string
		got  string
	}{
		{DefinitionFileName, renderDefinition(a)},
		{PromptFileName, renderPrompt(a)},
	}
	for _, c := range cases {
		assertGolden(t, c.name, []byte(c.got))
	}
}

// TestCatalogRenderDeterministic covers RF-8.2 / RNF-5: rendering the same agent
// twice yields identical bytes for both the definition and the prompt.
func TestCatalogRenderDeterministic(t *testing.T) {
	a := goldenAgent()
	if renderDefinition(a) != renderDefinition(a) {
		t.Error("renderDefinition is not deterministic")
	}
	if renderPrompt(a) != renderPrompt(a) {
		t.Error("renderPrompt is not deterministic")
	}
}

// assertGolden compares got against the golden snapshot for name, or rewrites it
// when -update is set.
func assertGolden(t *testing.T, name string, got []byte) {
	t.Helper()
	goldenPath := filepath.Join("testdata", "golden", filepath.FromSlash(name))

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
			t.Fatalf("mkdir golden dir: %v", err)
		}
		if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
			t.Fatalf("write golden %s: %v", goldenPath, err)
		}
		return
	}

	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden %s: %v (run with -update to generate)", goldenPath, err)
	}
	if string(want) != string(got) {
		t.Errorf("artifact %s does not match golden:\n--- got ---\n%s\n--- want ---\n%s",
			name, got, want)
	}
}
